#!/bin/bash

export GOOGLE_AUTH_CLIENT_SECRETS_FILE='client_secret.json'
export GOOGLE_AUTH_CREDENTIALS_FILE='credentials.json'
export GOOGLE_DRIVE_FOLDER_ID='1d57i-VAQRbCfLDIb9JCHGI3GPBK8cZ4O'
export GOOGLE_SHEETS_TEMPLATE_ID='1U0B7wu07bCH5X6Yfc3FQWgNEwMpoNCg8eDPtjlH0j6w'
export GOOGLE_SHEETS_SHEET_NAME='RIMS Data'
export GOOGLE_SHEETS_TSDB_PRIMARY_COLUMN='A'
export LOCAL_TSDB_FILE_PATH=''
export LOCAL_TSDB_FILE_FORMAT=''

python test.py
